### ISSUE TITLE
Avoid allocating a new array every time in `GetValues` and `GetNames`

### ISSUE THREAD

**Issue by Rekkonnect** [andrewlock/NetEscapades.EnumGenerators#19]
The `GetValues` and `GetNames` allocate a new array instead of caching it; a `private static readonly` field could be used, which would be initialized either lazily or immediately.

**Comment by mandragon00** [comment]
#18

**Comment by andrewlock** [comment]
As discussed in #21, this is by design, so I'm going to close this for now. Thanks anyway!
