### ISSUE TITLE
DisplayAttribute doesn't work

### ISSUE THREAD

**Issue by tabakaevga** [andrewlock/NetEscapades.EnumGenerators#22]
`DisplayAttribute` doesn't do what the main page says it should.

Sample code:
``` cs
Console.WriteLine(SomeColors.Red.ToStringFast());

[EnumExtensions]
public enum SomeColors
{
    [Display(Name = "Actually purple")]
    Red,
    Green,
}
```

Generated ouptut:
``` cs
public static string ToStringFast(this SomeColors value)
    => value switch
    {
        SomeColors.Red => nameof(SomeColors.Red),
        SomeColors.Green => nameof(SomeColors.Green),
        _ => value.ToString(),
    };
```
Console output:
![image](https://user-images.githubusercontent.com/24541725/172904988-dcea4684-4e04-4e53-9ff1-2d930b9c8c65.png)

SDK Version: 6.0.300

**Comment by FroggieFrog** [comment]
The latest release on NuGet is from **November 2021**, but the feature was added in **April 2022**.
So there need to be a new release on NuGet to use this feature.
