### ISSUE TITLE
ToStringFast does not take Display attribute into account.

### ISSUE THREAD

**Issue by vdWes911** [andrewlock/NetEscapades.EnumGenerators#24]
Hi @andrewlock .

I noticed that the instructions of using the NuGet package indicates that the Display attribute can be used to "override" the way the .ToStringFast returns the string.

I implemented everything as in the readme, but I cannot seem to get the [Display( Name = "Value" )] to work.

I used the following Enum:

```
public enum MyEnum
{
    Value1,

    [Display(Name = "Val2")]
    Value2,
}
```

The code is then generated as follows:

```
public static string ToStringFast(this MyEnum value)
            => value switch
            {
                MyEnum.Value1 => nameof(MyEnum.Value1),
                MyEnum.Value2 => nameof(MyEnum.Value2),
                _ => value.ToString(),
            };
```

I have tried both with and without the NETESCAPADES_ENUMGENERATORS_USAGES constant, same behavior every time.
I am using .NET 6.0 and the NuGet package (1.0.0-beta04) is installed in a Blazor Server app.

As indicated by FroggieFrog, the NuGet is still in pre-release, thus does not have the main branch's features yet. However this happens on the main branch (which has this feature) as well.

Am I missing something?

**Comment by FroggieFrog** [comment]
As mentioned in issue #22:

The latest release on NuGet is from **November 2021**, but the feature was added in **April 2022**.
So there need to be a new release on NuGet to use this feature.

**Comment by vdWes911** [comment]
I am reopening this issue, as I have checked out the main branch and created the NuGet package locally.

The code is still generated as I showed above.

**Comment by Skiendys** [comment]
yup same problem here, downlaoded main branch, built nuget for myself and still no luck with Display attribute.

**Comment by andrewlock** [comment]
I'm going to close this for now, as it definitely works in the main branch, and I'm going to do a new release soon! Your issues were likely due to caching of the old package when you tested locally 🙂
