### ISSUE TITLE
TryParseIgnoreCase is inaccessible due to its protection level

### ISSUE THREAD

**Issue by woodsongem** [andrewlock/NetEscapades.EnumGenerators#27]
Hello All,
I am trying to implement "NetEscapades.EnumGenerators" in .net core 3  and getting below errors. I am using MAC to run .net core 3.

**Error Message**:

CS0122: 'CustomerTypeExtensions.TryParseIgnoreCase(string?, out CustomerType)' is inaccessible due to its protection level

**Sample Code.**:
CustomerTypeExtensions.TryParseIgnoreCase("FullTime", out CustomerType customerType);

**Project Entry**:
    <PackageReference Include="NetEscapades.EnumGenerators" Version="1.0.0-beta04" PrivateAssets="all" ExcludeAssets="runtime" />

**Comment by AdrienTorris** [comment]
Hi,

`TryParseIgnore `case is private but it seems to be that way by design and not by mistake.

Can't you use the public `TryParse` method and pass the argument `ignoreCase` to true?

```
public static bool TryParse(
        [System.Diagnostics.CodeAnalysis.NotNullWhen(true)] string? name, 
        bool ignoreCase, 
        out MyEnum value)
```

**Comment by andrewlock** [comment]
As mentioned, the correct approach is to pass the `ignoreCase` flag. Thanks
