### ISSUE TITLE
Badly formed XML with version 1.0.0-beta05

### ISSUE THREAD

**Issue by ristogod** [andrewlock/NetEscapades.EnumGenerators#48]
After updating to version 1.0.0-beta05, when I do a build, I see these warnings in the Build Output.

```
XML comment has badly formed XML -- 'End tag 'c' does not match the start tag 'returns'.'
XML comment has badly formed XML -- 'End tag was not expected at this location.'
```

When I check the decompiled code for the generated classes, the three `IsDefine(...)` methods do not have XML comments applied, whereas all other methods do. Additionally, the line numbers in the Build Output warnings loosely correspond to the same methods observed in the decompiled code.

**Comment by andrewlock** [comment]
Doh, sorry about that, I'll put out a fix in beta06 shortly

**Comment by andrewlock** [comment]
Version 1.0.0-beta06 is now available, and fixes these. Sorry for the inconvenience
