### ISSUE TITLE
Feature request: Add extension for exhaustive switch

### ISSUE THREAD

**Issue by IkertxoDt** [andrewlock/NetEscapades.EnumGenerators#54]
Hello

Thanks a lot for you work (here and in your blog).

It is not related to performance but I think this will be a great place to create a exhaustive switch method extension (as you know the c# switch  is not exhaustive).

Something like this

```c#
public enum MyEnum
{
    Value1,
    Value2
}

//Params as values
public static T Switch(
    this MyEnum value,
    T Value1,
    T Value2) => value switch
{
    MyEnum.Value1 => Value1,
    MyEnum.Value2 => Value2,
    _ => throw new SwitchExpressionException(value)
}
 
//Params as functions
public static T Switch(
    this MyEnum value,
    Func<T> Value1,
    Func<T> Value2) => value switch
{
    MyEnum.Value1 => Value1(),
    MyEnum.Value2 => Value2(),
    _ => throw new SwitchExpressionException(value)
}
```

And the code using it

```c#
MyEnum myEnum;
int aux1 = myEnum.Switch(
    Value1: 5,
    Value2: 15);

int aux2 = myEnum.Switch(
    Value1: () => 5,
    Value2: () => 15);
```

It is true that this way the we "hide" the possibility of the `SwitchExpressionException`, but I think that If someone uses these methods is aware of the implications.

Thanks!

**Comment by andrewlock** [comment]
Thanks for the suggestion, but I don't think this is something I'd like to add to this library. This library is focused on replacing slower reflection-based APIs with source-generated versions, as opposed to a general collection of enum utils. Thanks anyway!

For the record, while I would like exhaustive switch statements too - I don't think this approach is worth the effort personally. If you don't provide switch values for all values, you'll get a build time warning:

```
Warning CS8509 : The switch expression does not handle all possible values of its input type
```

Which essentially is as good as the `Switch` method you've provided, except it's more flexible as well as more idiomatic. You can always enable warnings as errors too :)
