### ISSUE TITLE
Having both a class and a namespace with the same name results in CS0426.

### ISSUE THREAD

**Issue by NiceWaffel** [andrewlock/NetEscapades.EnumGenerators#61]
Reproducable in version 1.0.0-beta07 taken from nuget.org.

Take for example the following scenario:
```cs
namespace Foo
{
    public class Foo {}
  
    [EnumExtensions]
    public enum TestEnum
    {
        Value1
    }
}
```

The generator would generate something like this:

```cs
namespace Foo
{
    public static partial class TestEnumExtensions
    {
        public static string ToStringFast(this Foo.TestEnum value)
            => value switch
            {
                 Foo.TestEnum.Value1 => nameof(Foo.TestEnum.Value1),
                 _ => value.ToString(),
            };
    }
}
```

In this case `Foo` is seen as a class name instead of the namespace, resulting in the following error: `Error CS0426 : The type name 'TestEnum' does not exist in the type 'Foo'`.

This should be fixable by adding `global::` before `Foo.TestEnum`.

**Comment by andrewlock** [comment]
Thanks, this should be fixed in the next release!
