### ISSUE TITLE
Issue when coupling with System.Json.Text source generator

### ISSUE THREAD

**Issue by HakamFostok** [andrewlock/NetEscapades.EnumGenerators#69]
It took me 2 days to catch the problem.
I am using 
1.0.0-beta08
.NET 7
Visual studio 2022

here is a repo that reproduces the bug 
https://github.com/HakamFostok/NetEscapadesError

Add an enum in one class library
```
[NetEscapades.EnumGenerators.EnumExtensions]
public enum Enum1
{
    Value1,
    Value2,
}
```

Add class **In another class library (very important, if added in the same class library then everything is ok)**

```
public class JsonModel
{
    public Enum1 Enum { get; set; }
}
```

Now try to add System.Text.Json Source generator for the `JsonModel` class by doing the following

```
[JsonSerializable(typeof(JsonModel))]
public partial class MyJsonContext : JsonSerializerContext { }
```

the Json source generator will emit NOTHING.

go the the enum and remove or comment `[NetEscapades.EnumGenerators.EnumExtensions]` above the enum.
save the changes and wait a little bit, and the json source generator will emit the serializing.
If you do that while the Anaylizer is expanded for the both project, it will appears in more vivid way.

![image](https://github.com/andrewlock/NetEscapades.EnumGenerators/assets/12747172/908f08e2-85a0-47ac-8307-418389681deb)

There is a conflict between the 2 source generators, 
and the NetEscapades.EnumGenerator source-generator prevents the Json source-generator from working.

**Comment by andrewlock** [comment]
Hi @HakamFostok, that's very strange, frankly I don't understand how it can even be possible 😅

I'm getting a 404 when I try to view your repro - is it currently set to private?

Thanks

**Comment by HakamFostok** [comment]
@andrewlock Sorry a lot for that, even though I thought I made it public, it was still private. it is an embarrassing mistake, so sorry for this.
Now I am sure it is a public
![image](https://github.com/andrewlock/NetEscapades.EnumGenerators/assets/12747172/33c04cee-48f0-4f0b-b270-49dc2ccec8f1)

Thank you very much @andrewlock , really appreciate it

**Comment by andrewlock** [comment]
Thanks for the reproduction, unfortunately I have _no idea_ what's going on 😬 As I understand things, this shouldn't happen 🤷 Would you mind opening this issue at https://github.com/dotnet/runtime instead? Seeing as the non-generating issue is related to the System.Text.Json generator, maybe they can figure out what's going on? 🤔 Thanks!

**Comment by HakamFostok** [comment]
Thank you @andrewlock, I will open an issue there, just to let them know, although I think the .NET team is eager to close the issue without inspection, they are insanely fast in rejecting issues and dodging them (That is totally understandable because of the load of issues they get) but I will try my best to let them know.
I may tag you there if you do not mind, as this could give more credibility to the bug, and may let them consider it more seriously.
Thank you very much for all your contributions to .NET Andrew, you are always trying to make .NET better.

**Comment by HakamFostok** [comment]
I opened this bug at the dotnet runtime repo, and I can confirm that this is bug does not belong to this repo.
This bug belongs to the .NET repo.
Anyway updating to .NET 8 solved the problem magically, I have no idea how, but it worked.
Thank you a lot Andrew.
