### ISSUE TITLE
[Question] Guidenance on how to exclude generated code from code-coverage

### ISSUE THREAD

**Issue by alsami** [andrewlock/NetEscapades.EnumGenerators#70]
We are using this library in our projects and use coverlet.collector to analyze and track code coverage.

To exclude compiler generated code we usually can do so using a flag passing in [this attribute as a filter](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.compilergeneratedattribute?view=net-7.0). The classes generated do not use that attribute, which may make sense.

I could not find anything on the internet and was wondering if there is a known solution to exclude the classes that are auto generated.

**Comment by andrewlock** [comment]
Hi @alsami, is it possible to use [the `ExcludeFromCodeCoverageAttribute`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.excludefromcodecoverageattribute?view=net-7.0) as a filter also? The latest version emits that attribute, and while the code _is_ compiler generated in a way, I'm not sure if it would be best to add the `[CompilerGenerated]` attribute to the generated enums 🤔

**Comment by alsami** [comment]
> Hi @alsami, is it possible to use [the `ExcludeFromCodeCoverageAttribute`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.excludefromcodecoverageattribute?view=net-7.0) as a filter also? The latest version emits that attribute, and while the code _is_ compiler generated in a way, I'm not sure if it would be best to add the `[CompilerGenerated]` attribute to the generated enums 🤔

I saildy do not see the attribute `ExcludeFromCodeCoverageAttribute` used in the generated partial classes.

```csharp
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the NetEscapades.EnumGenerators source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
#if NETCOREAPP && !NETCOREAPP2_0 && !NETCOREAPP1_1 && !NETCOREAPP1_0
using System;
#endif

namespace A
{
    /// <summary>
    /// Extension methods for <see cref="global::Unidos.Domain.Chemicals.Enums.DosingBlockStartTriggerType" />
    /// </summary>
    public static partial class DosingBlockStartTriggerTypeExtensions
    {
// contentremoved
    }
}
```

But it is indeed used on the `EnumExtension` attribute

```csharp
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the NetEscapades.EnumGenerators source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

#if NETESCAPADES_ENUMGENERATORS_EMBED_ATTRIBUTES
namespace NetEscapades.EnumGenerators
{
    /// <summary>
    /// Add to enums to indicate that extension methods should be generated for the type
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Enum)]
    [global::System.Diagnostics.Conditional("NETESCAPADES_ENUMGENERATORS_USAGES")]
#if NET5_0_OR_GREATER
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Generated by the NetEscapades.EnumGenerators source generator.")]
#else
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
#endif
    public class EnumExtensionsAttribute : global::System.Attribute
    {
        /// <summary>
        /// The namespace to generate the extension class.
        /// If not provided the namespace of the enum will be used
        /// </summary>
        public string? ExtensionClassNamespace { get; set; }

        /// <summary>
        /// The name to use for the extension class.
        /// If not provided, the enum name with "Extensions" will be used.
        /// For example for an Enum called StatusCodes, the default name
        /// will be StatusCodesExtensions
        /// </summary>
        public string? ExtensionClassName { get; set; }
    }
}
#endif
```

We are running the latest beta 1.0.0-beta.8. Is there a newer version somewhere else?

**Comment by andrewlock** [comment]
Ah, my bad. FWIW, I _think_ you can work around this for now by adding the following to your app:

```csharp
[CompilerGenerated]
public static partial class DosingBlockStartTriggerTypeExtensions
{
}
```

**Comment by alsami** [comment]
Would you accept a PR that adds this attribute to the generated classes? I am happy to send one. It would be a bit tedious for us to always manually add these partial classes.

**Comment by andrewlock** [comment]
This PR https://github.com/andrewlock/NetEscapades.EnumGenerators/pull/83 should solve the issue I think - sorry for the delay!

**Comment by alsami** [comment]
Cool thanks! Are you planning to publish a new version any time soon?

**Comment by andrewlock** [comment]
Yup, just working on some extra bits, then will get it out some time this week!
