### ISSUE TITLE
[Question] Could make GetValues() and GetNames() faster if we generate and return static arrays

### ISSUE THREAD

**Issue by valentinmarinro** [andrewlock/NetEscapades.EnumGenerators#91]
Hi @andrewlock, I was thinking we can improve the speed for GetValues and GetNames by generating static arrays, but with the drawback of the initial allocation for these arrays (in case you never call these methods), while now if you call GetValues or GetNames multiple times you allocate a new array each time.

```csharp
    public enum Color
    {
        Red,
        Green,
        Blue
    }
    
    private static Color[] ColorsValues = new[]
    {
        Color.Red,
        Color.Green,
        Color.Blue
    };
    
    private static string[] ColorsNames = new[]
    {
        nameof(Color.Red),
        nameof(Color.Green),
        nameof(Color.Blue)
    };

    public static Color[] GetValues()
    {
        return ColorsValues;
    }
    
    public static string[] GetNames()
    {
        return ColorsNames;
    }
```

**Comment by henrikwidlund** [comment]
I think this was the behavior originally, but was changed to return a new array each time as you don't know what the consumer of said array will do with it. While you can't resize it, you can certainly modify its values via the indexer. It's thus safer to always return a new array and let the consumer cache it.
