### ISSUE TITLE
CS0618 - Enum members with obsolete attribute generates warnings

### ISSUE THREAD

**Issue by henrikwidlund** [andrewlock/NetEscapades.EnumGenerators#97]
If you have enum members that are marked as Obsolete the generators would generate warnings, this means that the code doesn't compile if you have warnings as errors.

Tested on 1.0.0-beta09.

**Comment by andrewlock** [comment]
Hey, yeah, that makes sense 🤔 The question is... how should we handle this 🤔 A _lot_ of the extension methods use all the members, regardless of whether they're used elsewhere

On the one hand, adding global ignoring of obsolete usages in the extension code probably makes sense as it's generated code.

On the other hand, maybe you _want_ to be aware that you're using obsolete members?
